version: '3.9'

services:
  webapi:
    container_name: dev-webapi
    build: 
      dockerfile: ops/dev/Dockerfile.webapi
      context: ../../
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://0.0.0.0:443;http://0.0.0.0:80
      #- ASPNETCORE_Kestrel__Certificates__Default__Password=123
      #- ASPNETCORE_Kestrel__Certificates__Default__Path=aspnetapp.pfx
    ports:
      - 5000:80
      - 5001:443
    volumes:
      - ../../src:/app
      - /app/obj/
      - /app/bin
    stdin_open: true 
    tty: true
    command: ["dotnet", "watch", "run", -v, "--project", "cycling-project-web-api.csproj", "--urls", "https://0.0.0.0:443;http://0.0.0.0:80"]
  
  db:
    container_name: dev-db
    image: postgres:16.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432
  
