// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace cycling_project_web_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250521182741_FixedForeignKeys")]
    partial class FixedForeignKeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("App.EntityModels.Mountain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_mountains");

                    b.HasAlternateKey("Name")
                        .HasName("ak_mountains_name");

                    b.ToTable("mountains", (string)null);
                });

            modelBuilder.Entity("App.EntityModels.MountainClimb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("AverageSlope")
                        .HasColumnType("real")
                        .HasColumnName("average_slope");

                    b.Property<int>("ClimbLengthMeter")
                        .HasColumnType("integer")
                        .HasColumnName("climb_length_meter");

                    b.Property<int>("DistanceFromStartMeters")
                        .HasColumnType("integer")
                        .HasColumnName("distance_from_start_meters");

                    b.Property<bool>("IsFinish")
                        .HasColumnType("boolean")
                        .HasColumnName("is_finish");

                    b.Property<int>("MountainId")
                        .HasColumnType("integer")
                        .HasColumnName("mountain_id");

                    b.Property<int>("StageId")
                        .HasColumnType("integer")
                        .HasColumnName("stage_id");

                    b.HasKey("Id")
                        .HasName("pk_mountain_climbs");

                    b.HasIndex("MountainId")
                        .HasDatabaseName("ix_mountain_climbs_mountain_id");

                    b.HasIndex("StageId")
                        .HasDatabaseName("ix_mountain_climbs_stage_id");

                    b.ToTable("mountain_climbs", (string)null);
                });

            modelBuilder.Entity("App.EntityModels.MountainClimbResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("BonusSeconds")
                        .HasColumnType("smallint")
                        .HasColumnName("bonus_seconds");

                    b.Property<int>("MountainClimbId")
                        .HasColumnType("integer")
                        .HasColumnName("mountain_climb_id");

                    b.Property<short>("MountainPoints")
                        .HasColumnType("smallint")
                        .HasColumnName("mountain_points");

                    b.Property<short>("Placement")
                        .HasColumnType("smallint")
                        .HasColumnName("placement");

                    b.HasKey("Id")
                        .HasName("pk_mountain_climb_reults");

                    b.HasIndex("MountainClimbId")
                        .HasDatabaseName("ix_mountain_climb_reults_mountain_climb_id");

                    b.ToTable("mountain_climb_reults", (string)null);
                });

            modelBuilder.Entity("App.EntityModels.Nation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<bool>("StillExists")
                        .HasColumnType("boolean")
                        .HasColumnName("still_exists");

                    b.HasKey("Id")
                        .HasName("pk_nations");

                    b.HasAlternateKey("Name")
                        .HasName("ak_nations_name");

                    b.ToTable("nations", (string)null);
                });

            modelBuilder.Entity("App.EntityModels.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<int>("NationId")
                        .HasColumnType("integer")
                        .HasColumnName("nation_id");

                    b.HasKey("Id")
                        .HasName("pk_races");

                    b.HasAlternateKey("Name")
                        .HasName("ak_races_name");

                    b.HasIndex("NationId")
                        .HasDatabaseName("ix_races_nation_id");

                    b.ToTable("races", (string)null);
                });

            modelBuilder.Entity("App.EntityModels.RaceEdition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<int>("RaceId")
                        .HasColumnType("integer")
                        .HasColumnName("race_id");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<short>("Year")
                        .HasColumnType("smallint")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_race_editions");

                    b.HasAlternateKey("RaceId", "Year")
                        .HasName("ak_race_editions_race_id_year");

                    b.ToTable("race_editions", (string)null);
                });

            modelBuilder.Entity("App.EntityModels.RaceRiderParticipation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("RaceTeamParticipationId")
                        .HasColumnType("integer")
                        .HasColumnName("race_team_participation_id");

                    b.Property<int>("RiderId")
                        .HasColumnType("integer")
                        .HasColumnName("rider_id");

                    b.HasKey("Id")
                        .HasName("pk_race_rider_participations");

                    b.HasAlternateKey("RaceTeamParticipationId", "RiderId")
                        .HasName("ak_race_rider_participations_race_team_participation_id_rider_");

                    b.HasIndex("RiderId")
                        .HasDatabaseName("ix_race_rider_participations_rider_id");

                    b.ToTable("race_rider_participations", (string)null);
                });

            modelBuilder.Entity("App.EntityModels.RaceTeamParticipation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("RaceEditionId")
                        .HasColumnType("integer")
                        .HasColumnName("race_edition_id");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.HasKey("Id")
                        .HasName("pk_race_team_participations");

                    b.HasAlternateKey("RaceEditionId", "TeamId")
                        .HasName("ak_race_team_participations_race_edition_id_team_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_race_team_participations_team_id");

                    b.ToTable("race_team_participations", (string)null);
                });

            modelBuilder.Entity("App.EntityModels.Rider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("last_name");

                    b.Property<int>("NationId")
                        .HasColumnType("integer")
                        .HasColumnName("nation_id");

                    b.HasKey("Id")
                        .HasName("pk_riders");

                    b.HasIndex("NationId")
                        .HasDatabaseName("ix_riders_nation_id");

                    b.ToTable("riders", (string)null);
                });

            modelBuilder.Entity("App.EntityModels.RiderTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("JoinDate")
                        .HasColumnType("date")
                        .HasColumnName("join_date");

                    b.Property<DateOnly>("LeaveDate")
                        .HasColumnType("date")
                        .HasColumnName("leave_date");

                    b.Property<int>("RiderId")
                        .HasColumnType("integer")
                        .HasColumnName("rider_id");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.HasKey("Id")
                        .HasName("pk_riders_teams");

                    b.HasIndex("RiderId")
                        .HasDatabaseName("ix_riders_teams_rider_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_riders_teams_team_id");

                    b.ToTable("riders_teams", (string)null);
                });

            modelBuilder.Entity("App.EntityModels.Sprint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DistanceFromStartMeters")
                        .HasColumnType("integer")
                        .HasColumnName("distance_from_start_meters");

                    b.Property<bool>("IsFinish")
                        .HasColumnType("boolean")
                        .HasColumnName("is_finish");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<int>("StageId")
                        .HasColumnType("integer")
                        .HasColumnName("stage_id");

                    b.HasKey("Id")
                        .HasName("pk_sprints");

                    b.HasIndex("StageId")
                        .HasDatabaseName("ix_sprints_stage_id");

                    b.ToTable("sprints", (string)null);
                });

            modelBuilder.Entity("App.EntityModels.SprintResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("BonusSeconds")
                        .HasColumnType("smallint")
                        .HasColumnName("bonus_seconds");

                    b.Property<short>("Placement")
                        .HasColumnType("smallint")
                        .HasColumnName("placement");

                    b.Property<short>("Points")
                        .HasColumnType("smallint")
                        .HasColumnName("points");

                    b.Property<int>("RaceRiderParticipationId")
                        .HasColumnType("integer")
                        .HasColumnName("race_rider_participation_id");

                    b.Property<int>("SprintId")
                        .HasColumnType("integer")
                        .HasColumnName("sprint_id");

                    b.HasKey("Id")
                        .HasName("pk_sprint_results");

                    b.HasAlternateKey("SprintId", "RaceRiderParticipationId")
                        .HasName("ak_sprint_results_sprint_id_race_rider_participation_id");

                    b.HasIndex("RaceRiderParticipationId")
                        .HasDatabaseName("ix_sprint_results_race_rider_participation_id");

                    b.ToTable("sprint_results", (string)null);
                });

            modelBuilder.Entity("App.EntityModels.Stage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int>("DistanceMeters")
                        .HasColumnType("integer")
                        .HasColumnName("distance_meters");

                    b.Property<string>("FinishLocation")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("finish_location");

                    b.Property<int>("RaceEditionId")
                        .HasColumnType("integer")
                        .HasColumnName("race_edition_id");

                    b.Property<short>("StageNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("stage_number");

                    b.Property<int>("StageTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("stage_type_id");

                    b.Property<string>("StartLocation")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("start_location");

                    b.HasKey("Id")
                        .HasName("pk_stages");

                    b.HasAlternateKey("RaceEditionId", "StageNumber")
                        .HasName("ak_stages_race_edition_id_stage_number");

                    b.HasIndex("StageTypeId")
                        .HasDatabaseName("ix_stages_stage_type_id");

                    b.ToTable("stages", (string)null);
                });

            modelBuilder.Entity("App.EntityModels.StageCombativeAward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("RaceRiderParticipationId")
                        .HasColumnType("integer")
                        .HasColumnName("race_rider_participation_id");

                    b.Property<int>("StageId")
                        .HasColumnType("integer")
                        .HasColumnName("stage_id");

                    b.HasKey("Id")
                        .HasName("pk_stage_combative_awards");

                    b.HasIndex("RaceRiderParticipationId")
                        .HasDatabaseName("ix_stage_combative_awards_race_rider_participation_id");

                    b.HasIndex("StageId")
                        .IsUnique()
                        .HasDatabaseName("ix_stage_combative_awards_stage_id");

                    b.ToTable("stage_combative_awards", (string)null);
                });

            modelBuilder.Entity("App.EntityModels.StageDidNotStart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("RaceRiderParticipationId")
                        .HasColumnType("integer")
                        .HasColumnName("race_rider_participation_id");

                    b.Property<int>("StageId")
                        .HasColumnType("integer")
                        .HasColumnName("stage_id");

                    b.HasKey("Id")
                        .HasName("pk_stage_did_not_starts");

                    b.HasAlternateKey("StageId", "RaceRiderParticipationId")
                        .HasName("ak_stage_did_not_starts_stage_id_race_rider_participation_id");

                    b.HasIndex("RaceRiderParticipationId")
                        .HasDatabaseName("ix_stage_did_not_starts_race_rider_participation_id");

                    b.ToTable("stage_did_not_starts", (string)null);
                });

            modelBuilder.Entity("App.EntityModels.StageResultStatusCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<string>("NameAbbreviation")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name_abbreviation");

                    b.HasKey("Id")
                        .HasName("pk_stage_result_status_codes");

                    b.HasAlternateKey("Name")
                        .HasName("ak_stage_result_status_codes_name");

                    b.HasAlternateKey("NameAbbreviation")
                        .HasName("ak_stage_result_status_codes_name_abbreviation");

                    b.ToTable("stage_result_status_codes", (string)null);
                });

            modelBuilder.Entity("App.EntityModels.StageRiderResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FinishTimeMilliseconds")
                        .HasColumnType("integer")
                        .HasColumnName("finish_time_milliseconds");

                    b.Property<short>("Placement")
                        .HasColumnType("smallint")
                        .HasColumnName("placement");

                    b.Property<int>("RaceRiderParticipationId")
                        .HasColumnType("integer")
                        .HasColumnName("race_rider_participation_id");

                    b.Property<int>("StageFinishStatusCodeId")
                        .HasColumnType("integer")
                        .HasColumnName("stage_finish_status_code_id");

                    b.Property<int>("StageId")
                        .HasColumnType("integer")
                        .HasColumnName("stage_id");

                    b.Property<int>("StageResultStatusCodeId")
                        .HasColumnType("integer")
                        .HasColumnName("stage_result_status_code_id");

                    b.HasKey("Id")
                        .HasName("pk_stage_rider_results");

                    b.HasAlternateKey("StageId", "RaceRiderParticipationId")
                        .HasName("ak_stage_rider_results_stage_id_race_rider_participation_id");

                    b.HasIndex("RaceRiderParticipationId")
                        .HasDatabaseName("ix_stage_rider_results_race_rider_participation_id");

                    b.HasIndex("StageResultStatusCodeId")
                        .HasDatabaseName("ix_stage_rider_results_stage_result_status_code_id");

                    b.ToTable("stage_rider_results", (string)null);
                });

            modelBuilder.Entity("App.EntityModels.StageRiderStanding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("BonusSeconds")
                        .HasColumnType("smallint")
                        .HasColumnName("bonus_seconds");

                    b.Property<short>("MountainPoints")
                        .HasColumnType("smallint")
                        .HasColumnName("mountain_points");

                    b.Property<short>("MountainPointsPenalty")
                        .HasColumnType("smallint")
                        .HasColumnName("mountain_points_penalty");

                    b.Property<int>("RaceRiderParticipationId")
                        .HasColumnType("integer")
                        .HasColumnName("race_rider_participation_id");

                    b.Property<short>("SprintPoints")
                        .HasColumnType("smallint")
                        .HasColumnName("sprint_points");

                    b.Property<short>("SprintPointsPenalty")
                        .HasColumnType("smallint")
                        .HasColumnName("sprint_points_penalty");

                    b.Property<int>("StageId")
                        .HasColumnType("integer")
                        .HasColumnName("stage_id");

                    b.Property<int>("TimeMilliseconds")
                        .HasColumnType("integer")
                        .HasColumnName("time_milliseconds");

                    b.Property<short>("TimePenaltySeconds")
                        .HasColumnType("smallint")
                        .HasColumnName("time_penalty_seconds");

                    b.HasKey("Id")
                        .HasName("pk_stage_rider_standings");

                    b.HasAlternateKey("StageId", "RaceRiderParticipationId")
                        .HasName("ak_stage_rider_standings_stage_id_race_rider_participation_id");

                    b.HasIndex("RaceRiderParticipationId")
                        .HasDatabaseName("ix_stage_rider_standings_race_rider_participation_id");

                    b.ToTable("stage_rider_standings", (string)null);
                });

            modelBuilder.Entity("App.EntityModels.StageTeamResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FinishTimeMilliseconds")
                        .HasColumnType("integer")
                        .HasColumnName("finish_time_milliseconds");

                    b.Property<short>("Placement")
                        .HasColumnType("smallint")
                        .HasColumnName("placement");

                    b.Property<int>("RaceTeamParticipationId")
                        .HasColumnType("integer")
                        .HasColumnName("race_team_participation_id");

                    b.Property<int>("StageId")
                        .HasColumnType("integer")
                        .HasColumnName("stage_id");

                    b.HasKey("Id")
                        .HasName("pk_stage_team_results");

                    b.HasAlternateKey("StageId", "RaceTeamParticipationId")
                        .HasName("ak_stage_team_results_stage_id_race_team_participation_id");

                    b.HasIndex("RaceTeamParticipationId")
                        .HasDatabaseName("ix_stage_team_results_race_team_participation_id");

                    b.ToTable("stage_team_results", (string)null);
                });

            modelBuilder.Entity("App.EntityModels.StageTeamStanding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("BonusSeconds")
                        .HasColumnType("smallint")
                        .HasColumnName("bonus_seconds");

                    b.Property<short>("MountainPoints")
                        .HasColumnType("smallint")
                        .HasColumnName("mountain_points");

                    b.Property<short>("MountainPointsPenalty")
                        .HasColumnType("smallint")
                        .HasColumnName("mountain_points_penalty");

                    b.Property<int>("RaceTeamParticipationId")
                        .HasColumnType("integer")
                        .HasColumnName("race_team_participation_id");

                    b.Property<short>("SprintPoints")
                        .HasColumnType("smallint")
                        .HasColumnName("sprint_points");

                    b.Property<short>("SprintPointsPenalty")
                        .HasColumnType("smallint")
                        .HasColumnName("sprint_points_penalty");

                    b.Property<int>("StageId")
                        .HasColumnType("integer")
                        .HasColumnName("stage_id");

                    b.Property<int>("TimeMilliseconds")
                        .HasColumnType("integer")
                        .HasColumnName("time_milliseconds");

                    b.Property<short>("TimePenaltySeconds")
                        .HasColumnType("smallint")
                        .HasColumnName("time_penalty_seconds");

                    b.HasKey("Id")
                        .HasName("pk_stage_team_standings");

                    b.HasAlternateKey("StageId", "RaceTeamParticipationId")
                        .HasName("ak_stage_team_standings_stage_id_race_team_participation_id");

                    b.HasIndex("RaceTeamParticipationId")
                        .HasDatabaseName("ix_stage_team_standings_race_team_participation_id");

                    b.ToTable("stage_team_standings", (string)null);
                });

            modelBuilder.Entity("App.EntityModels.StageType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_stage_types");

                    b.HasAlternateKey("Name")
                        .HasName("ak_stage_types_name");

                    b.ToTable("stage_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Flat"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hilly"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mountain"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Individual time trial"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Team time trial"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Individual mountain time trial"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Cobblestone"
                        });
                });

            modelBuilder.Entity("App.EntityModels.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<int>("TeamOrganizationId")
                        .HasColumnType("integer")
                        .HasColumnName("team_organization_id");

                    b.Property<short>("Year")
                        .HasColumnType("smallint")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_teams");

                    b.HasAlternateKey("TeamOrganizationId", "Year")
                        .HasName("ak_teams_team_organization_id_year");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("App.EntityModels.TeamOrganization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id")
                        .HasName("pk_team_organizations");

                    b.ToTable("team_organizations", (string)null);
                });

            modelBuilder.Entity("App.EntityModels.MountainClimb", b =>
                {
                    b.HasOne("App.EntityModels.Mountain", "Mountain")
                        .WithMany("MountainClimbs")
                        .HasForeignKey("MountainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mountain_climbs_mountains_mountain_id");

                    b.HasOne("App.EntityModels.Stage", "Stage")
                        .WithMany("MountainClimbs")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mountain_climbs_stages_stage_id");

                    b.Navigation("Mountain");

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("App.EntityModels.MountainClimbResult", b =>
                {
                    b.HasOne("App.EntityModels.MountainClimb", "MountainClimb")
                        .WithMany()
                        .HasForeignKey("MountainClimbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_mountain_climb_reults_mountain_climbs_mountain_climb_id");

                    b.Navigation("MountainClimb");
                });

            modelBuilder.Entity("App.EntityModels.Race", b =>
                {
                    b.HasOne("App.EntityModels.Nation", "Nation")
                        .WithMany()
                        .HasForeignKey("NationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_races_nations_nation_id");

                    b.Navigation("Nation");
                });

            modelBuilder.Entity("App.EntityModels.RaceEdition", b =>
                {
                    b.HasOne("App.EntityModels.Race", "Race")
                        .WithMany("RaceEditions")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_race_editions_races_race_id");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("App.EntityModels.RaceRiderParticipation", b =>
                {
                    b.HasOne("App.EntityModels.RaceTeamParticipation", "RaceTeamParticipation")
                        .WithMany("RaceRiderParticipations")
                        .HasForeignKey("RaceTeamParticipationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_race_rider_participations_race_team_participations_race_tea");

                    b.HasOne("App.EntityModels.Rider", "Rider")
                        .WithMany()
                        .HasForeignKey("RiderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_race_rider_participations_riders_rider_id");

                    b.Navigation("RaceTeamParticipation");

                    b.Navigation("Rider");
                });

            modelBuilder.Entity("App.EntityModels.RaceTeamParticipation", b =>
                {
                    b.HasOne("App.EntityModels.RaceEdition", "RaceEdition")
                        .WithMany()
                        .HasForeignKey("RaceEditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_race_team_participations_race_editions_race_edition_id");

                    b.HasOne("App.EntityModels.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_race_team_participations_teams_team_id");

                    b.Navigation("RaceEdition");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("App.EntityModels.Rider", b =>
                {
                    b.HasOne("App.EntityModels.Nation", "Nation")
                        .WithMany()
                        .HasForeignKey("NationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_riders_nations_nation_id");

                    b.Navigation("Nation");
                });

            modelBuilder.Entity("App.EntityModels.RiderTeam", b =>
                {
                    b.HasOne("App.EntityModels.Rider", "Rider")
                        .WithMany("RiderTeam")
                        .HasForeignKey("RiderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_riders_teams_riders_rider_id");

                    b.HasOne("App.EntityModels.Team", "Team")
                        .WithMany("RiderTeam")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_riders_teams_teams_team_id");

                    b.Navigation("Rider");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("App.EntityModels.Sprint", b =>
                {
                    b.HasOne("App.EntityModels.Stage", "Stage")
                        .WithMany("Sprints")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sprints_stages_stage_id");

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("App.EntityModels.SprintResult", b =>
                {
                    b.HasOne("App.EntityModels.RaceRiderParticipation", "RaceRiderParticipation")
                        .WithMany()
                        .HasForeignKey("RaceRiderParticipationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sprint_results_race_rider_participations_race_rider_partici");

                    b.HasOne("App.EntityModels.Sprint", "Sprint")
                        .WithMany("SprintResults")
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sprint_results_sprints_sprint_id");

                    b.Navigation("RaceRiderParticipation");

                    b.Navigation("Sprint");
                });

            modelBuilder.Entity("App.EntityModels.Stage", b =>
                {
                    b.HasOne("App.EntityModels.RaceEdition", "RaceEdition")
                        .WithMany("Stages")
                        .HasForeignKey("RaceEditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stages_race_editions_race_edition_id");

                    b.HasOne("App.EntityModels.StageType", "StageType")
                        .WithMany()
                        .HasForeignKey("StageTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stages_stage_types_stage_type_id");

                    b.Navigation("RaceEdition");

                    b.Navigation("StageType");
                });

            modelBuilder.Entity("App.EntityModels.StageCombativeAward", b =>
                {
                    b.HasOne("App.EntityModels.RaceRiderParticipation", "RaceRiderParticipation")
                        .WithMany()
                        .HasForeignKey("RaceRiderParticipationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stage_combative_awards_race_rider_participations_race_rider");

                    b.HasOne("App.EntityModels.Stage", "Stage")
                        .WithMany()
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stage_combative_awards_stages_stage_id");

                    b.Navigation("RaceRiderParticipation");

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("App.EntityModels.StageDidNotStart", b =>
                {
                    b.HasOne("App.EntityModels.RaceRiderParticipation", "RaceRiderParticipation")
                        .WithMany()
                        .HasForeignKey("RaceRiderParticipationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stage_did_not_starts_race_rider_participations_race_rider_p");

                    b.HasOne("App.EntityModels.Stage", "Stage")
                        .WithMany()
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stage_did_not_starts_stages_stage_id");

                    b.Navigation("RaceRiderParticipation");

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("App.EntityModels.StageRiderResult", b =>
                {
                    b.HasOne("App.EntityModels.RaceRiderParticipation", "RaceRiderParticipation")
                        .WithMany()
                        .HasForeignKey("RaceRiderParticipationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stage_rider_results_race_rider_participations_race_rider_pa");

                    b.HasOne("App.EntityModels.Stage", "Stage")
                        .WithMany("StageRiderResults")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stage_rider_results_stages_stage_id");

                    b.HasOne("App.EntityModels.StageResultStatusCode", "StageResultStatusCode")
                        .WithMany()
                        .HasForeignKey("StageResultStatusCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stage_rider_results_stage_result_status_codes_stage_result_");

                    b.Navigation("RaceRiderParticipation");

                    b.Navigation("Stage");

                    b.Navigation("StageResultStatusCode");
                });

            modelBuilder.Entity("App.EntityModels.StageRiderStanding", b =>
                {
                    b.HasOne("App.EntityModels.RaceRiderParticipation", "RaceRiderParticipation")
                        .WithMany()
                        .HasForeignKey("RaceRiderParticipationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stage_rider_standings_race_rider_participations_race_rider_");

                    b.HasOne("App.EntityModels.Stage", "Stage")
                        .WithMany()
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stage_rider_standings_stages_stage_id");

                    b.Navigation("RaceRiderParticipation");

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("App.EntityModels.StageTeamResult", b =>
                {
                    b.HasOne("App.EntityModels.RaceTeamParticipation", "RaceTeamParticipation")
                        .WithMany()
                        .HasForeignKey("RaceTeamParticipationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stage_team_results_race_team_participations_race_team_parti");

                    b.HasOne("App.EntityModels.Stage", "Stage")
                        .WithMany("StageTeamResults")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stage_team_results_stages_stage_id");

                    b.Navigation("RaceTeamParticipation");

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("App.EntityModels.StageTeamStanding", b =>
                {
                    b.HasOne("App.EntityModels.RaceTeamParticipation", "RaceTeamParticipation")
                        .WithMany()
                        .HasForeignKey("RaceTeamParticipationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stage_team_standings_race_team_participations_race_team_par");

                    b.HasOne("App.EntityModels.Stage", "Stage")
                        .WithMany()
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stage_team_standings_stages_stage_id");

                    b.Navigation("RaceTeamParticipation");

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("App.EntityModels.Team", b =>
                {
                    b.HasOne("App.EntityModels.TeamOrganization", null)
                        .WithMany("Teams")
                        .HasForeignKey("TeamOrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_teams_team_organizations_team_organization_id");
                });

            modelBuilder.Entity("App.EntityModels.Mountain", b =>
                {
                    b.Navigation("MountainClimbs");
                });

            modelBuilder.Entity("App.EntityModels.Race", b =>
                {
                    b.Navigation("RaceEditions");
                });

            modelBuilder.Entity("App.EntityModels.RaceEdition", b =>
                {
                    b.Navigation("Stages");
                });

            modelBuilder.Entity("App.EntityModels.RaceTeamParticipation", b =>
                {
                    b.Navigation("RaceRiderParticipations");
                });

            modelBuilder.Entity("App.EntityModels.Rider", b =>
                {
                    b.Navigation("RiderTeam");
                });

            modelBuilder.Entity("App.EntityModels.Sprint", b =>
                {
                    b.Navigation("SprintResults");
                });

            modelBuilder.Entity("App.EntityModels.Stage", b =>
                {
                    b.Navigation("MountainClimbs");

                    b.Navigation("Sprints");

                    b.Navigation("StageRiderResults");

                    b.Navigation("StageTeamResults");
                });

            modelBuilder.Entity("App.EntityModels.Team", b =>
                {
                    b.Navigation("RiderTeam");
                });

            modelBuilder.Entity("App.EntityModels.TeamOrganization", b =>
                {
                    b.Navigation("Teams");
                });
#pragma warning restore 612, 618
        }
    }
}
